# Generated by Django 3.1.4 on 2021-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrcapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='user_checked',
            field=models.BooleanField(default=False),
        ),
    ]
